# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-24 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0002_auto_20180123_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='pregunta',
            field=models.CharField(max_length=255),
        ),
    ]
